services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 77cs/ecommerce-app:latest
    container_name: ecommerce-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Database=ecommerce;User=ecommerceuser;Password=ecommercepassword;

  mysql-db:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerceuser
      MYSQL_PASSWORD: ecommercepassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
